(* generated by Ott 0.32 from: /home/roger/hdm/ott/Funs.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.



Inductive n : Set := 
 | n_Zero : n
 | n_Succ : n -> n.

Definition A : Set := list skvar.
(** definitions *)

(** funs Add *)
Fixpoint addA (x1:A) (x2:A) : A:=
  match x1,x2 with
  | A1 , A2 => A1
end.

(** definitions *)

(* defns WellFormedness *)
Inductive Wf : A -> Prop :=    (* defn Wf *)
 | WfId : forall (A1 A2:A),
     Wf A1 ->
     Wf A2 ->
     Wf  (addA A1 A2 ) .


